openapi: 3.1.0
info:
  title: Fleet Database
  description: API endpoints for Fleet Database Management
  version: 1.0.0
servers:
  - url: 'https://www.jacobwg.net'
paths:
  /vehicle:
    get:
      summary: Get vehicle
      description: Get details of an individual vehicle.
      parameters:
        - $ref: "#/components/parameters/vehicleId"
        - $ref: "#/components/parameters/vehicleYear"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/vehicle"
              example:
                id: 1
                year: 2024
                make: 'Freightliner'
                model: 'Cascadia'
                currentData:
                  currentOdometer: 568.4
                startData:
                  startDate: 'January 1, 2025'
                  startOdometer: 25.0
    post:
      summary: Add or update vehicle
      description: Add a new vehicle or change details of an existing one.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/vehicle'
      responses:
        "201":
          description: Created
components:
  schemas:
    vehicle:
      type: object
      properties:
        id:
          type: integer
        year:
          type: integer
        make:
          type: string
        model:
          type: string
        currentData:
          type: object
          properties:
            currentOdometer:
              type: number
        startData:
          type: object
          properties:
            startDate:
              type: string
            startOdometer:
              type: number
  parameters:
    vehicleId:
      name: id
      in: query
      schema:
        type: integer
        format: int32
        minimum: 1
    vehicleYear:
      name: year
      in: query
      schema:
        type: integer
        format: int32
        minimum: 1900
        pattern: '\d{4}'